<p>
<table cellspacing="0" class="pagetable">
<thead>
<tr class='vert'>
<th>Id</th><th colspan="4">Reference</th><th colspan="8">Description</th><th></th>
</tr>
</thead>
<tbody>
<? foreach($list_pr as $row):?>
	<tr><td><?= $row->id ?></td>
	<td colspan="4"><a href="<?= Atomik::url('edit_data',array('id'=>$row->data_id)) ?>" ><?=  $row->reference." ".$row->type." i".$row->version ?></a></td>
	<td colspan="8"><?= $row->project." ".$row->lru." ".$row->description ?></td>
	<td><a href="<?= Atomik::url('edit_data',array('id'=>$row->data_id)) ?>&impact_highlight=active&remove_pr=yes&remove_link_id=<?= $row->id?>" onclick="confirm_suppress_pr(<?= $pr_id?>,<?php echo $row->id?>);return false;" >
	<img style='padding-left:5px;padding-top:5px' border='0' width='20' height='20' src='assets/images/32x32/agt_action_fail.png' alt='remove link' title='remove link' />
	</a></td>
	</tr>
<? endforeach?>
</tbody>
</table>
<?php
if ($pr_treatment != "no"){
	?>
	<p><a href="#" style="text-decoration: none;outline-width: medium;outline-style: none;" title="Add a link"><img src="assets/images/newobject.gif" class="systemicon" alt="Add a link" title="Add a link" border="no" onclick="new_pr_link_form.submit()"/> Add a link to a target</a></p>
	<form method="POST" action="<?= Atomik::url('edit_data') ?>?tab=impact" name="new_pr_link_form">
	<fieldset>	
	<label for='data_impacted_id'>Data impacted</label>
	<select class='combobox' style="width:300px" name='data_impacted_id'>
	<option value='' /> --All--
	<? foreach ($list_data as $row): 
  	  print "<option value='{$row['id']}'";
      if ($row['id'] == $previous_data_id){
  		   	print " SELECTED";
  		}
      if ($row['description'] == "")
         $description = $row['type_description'];
      else
         $description = $row['description'];    
        $date_published= Date::convert_date_conviviale ($row['date_published']);
      print ">".$row['type']." <b>".$row['reference']."</b> issue ".$row['version']." ".$description." ".$date_published;  		
 	endforeach?>
	</select>
	</fieldset>
<input type="hidden" name='add_pr_link' 	value='yes'/>
<input type="hidden" name='id' 				value='<?= $pr_id?>'/>
</form>	
</p>
<?
}?>