<? if ($user_to_edit->projects != NULL) {?>
<table cellspacing="0" class="pagetable" style="float:left;width:500px">
<thead>
<tr class='vert'>
<th>Project assigned<th></th>
</tr>
</thead>
<tbody>
<?php
if ($user_to_edit->projects != null){
	foreach( $user_to_edit->projects as $row):
		$color = ($counter%2)?"vert":"rouge";?>	
		<tr class='<?= $color?>'><td><span style='color:#000'><?= $row['company']." ".$row['aircraft']." ".$row['project']?></span></td>
		<td><a class="<?= A('css_admin')?>" href="<?= Atomik::url('user/remove_project_assign',array('user_id'=>$user_to_edit->id,'id'=>$row['id']))?>" >
		<img style='padding-left:5px;padding-top:5px;float:right' border="0" width='20' height='20' src='<?= Atomik::asset("assets/images/32x32/agt_action_fail.png")?>' alt='remove link' title='remove link' /></a></td>
		</tr>
		<? $counter++;
	endforeach;
}
?>
</tbody>
</table>
<?
}?>
