<style type="text/css">
li.box {
	margin: 2px 2px 5px 2px;
	padding: 10px 10px 10px 35px;
	border: 1px solid #E8EFDE;
	color: #000;
	width: auto;
	background: #F9FBF7;
	/* height: 1%; */ /*IE6*/
}
</style>
<ul>
<li class="box" style="list-style-type: none;height:350px">
<div>
<div style="float:right;margin-right:40px;padding:10px">
<a href="<?= "../result/".$excel_filename ?>" >
<img alt="Export openxml" title="Export openxml" border="0" src="<?= Atomik::asset('assets/images/256x256/Excel2007.png')?>" class='no_img_button' width="256" height="256" />
</a>
</div>
<div style="margin:10px;width:300px">
<b><?= $excel_filename?></b> report has been generated.<br/>
Click here to open the Microsoft Excel workbook:
</div>
</div>
</li>
</ul>
<script type="text/javascript">
<!-- 
window.top.window.ActionExportEnd("OK");
//-->
</script>
