<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<link rel="stylesheet" type="text/css" href="../assets/css/main.css" />
</head>
<body>
<div id="bande_gauche" style="width:350px;float:left">
<div class="my_menu">
<ul>
<li class="email"><h2><a href="<?= Atomik::url('mail/send_data',array('id'=>$id,'filename'=>$filename,'draft'=>'yes')) ?>"  onclick="window.top.window.uploadRun('Sending email ... Please wait ...')">Send by email</a></h2></li>
</ul></div></div>
</body>
</html>
<script type="text/javascript">
<!-- 
window.top.window.uploadEnd("OK","Export complete.");
//-->
</script>

