<div class="contenu">
<h2>Peer Review summary</h2>
<p>The amount of remarks is <b><?= $remarks->amount_remarks ?></b>
<iframe id="export_data_list_frame" name="export_data_list_frame" src="../blank.php" style="display:none;border:none;width:100%;min-height:300px;overflow:hidden"></iframe>
	<p>Data version covered are (Click to see remarks):</p>
	<table cellspacing="0" class="pagetable" style="width:80%;float:left">
	<thead>
	<tr class='vert'>
	<th colspan="10">Name</th><th>Nb</th><th colspan="3">Peer reviews</th><th colspan="3">Inspections</th>
	</tr>
	</thead>
	<tbody>
	<? foreach ($remarks->list_draft_data() as $id => $row):
		$color = ($line_counter++ % 2 == 0)? "rouge" : "vert";
		?>
		<tr class="<?= $color ?>">
		<td colspan="10"><?= $row['name'] ?></td>
		<td><?= $row['nb_remarks']?></td>
		<td colspan="3">
			<form method="POST" action="<?= Atomik::url('export/export_xlsx_peer_review_report')?>" onsubmit="uploadRun('Exporting Peer Review Report ... Please wait ...')" target="export_data_list_frame">  		
				<span class="art-button-wrapper">
				<span class="l"> </span>
				<span class="r"> </span>
				<input class="art-button" type="submit" name="submit_export" value="Export"/>
				</span>
				<input type="hidden" name="id" value="<?=$id?>"/>
			</form>
		</td>
		<td colspan="3">
			<form method="POST" action="<?= Atomik::url('export/export_xlsx_inspection_report')?>" onsubmit="uploadRun('Exporting Inpsection Report ... Please wait ...');document.getElementById('export_data_list_frame').style.display = 'block'" target="export_data_list_frame">  		
				<span class="art-button-wrapper">
				<span class="l"> </span>
				<span class="r"> </span>
				<input class="art-button" type="submit" name="submit_export_inspection" value="Export"/>
				</span>
				<input type="hidden" name="id" value="<?=$id?>"/>
			</form>
		</td>		
		</tr>
	<? endforeach?>
	</tbody>
	</table>
	<div style="padding:5px">
		<div style="width:80%;float:right">
		<img class="bar" src="<?= $bar_filename ?>" alt="Remarks graph"  />
		</div>
		<div style="width:20%;float:left">
		<table cellspacing="0" class="pagetable">
		<thead>
		<tr class='vert'>
		<th colspan="2">Type</th><th>nb</th>
		</tr>
		</thead>
		<tbody>
		<? foreach ($remarks->remark_tab as $name => $amount):
			$color = ($line_counter++ % 2 == 0)? "rouge" : "vert";
			?>
			<tr class="<?= $color ?>"><td colspan="2"><?= $name ?></td><td><?= $amount ?></td></tr>
		<? endforeach?>
		</tbody>
		</table>
		</div>
		<div class="spacer"></div>
	</div>
	<h2>Peer reviewers</h2>
	<div style="padding:5px">
		<div style="width:70%;float:right">
		<img class="pie" src="<?= $pie_filename ?>" alt="Peer reviewers graph" />
		</div>
		<div style="width:30%;float:left">
		<table cellspacing="0" class="pagetable">
		<thead>
		<tr class='vert'>
		<th colspan="3">Name</th><th colspan="3">Function</th><th>Nb</th>
		</tr>
		</thead>
		<tbody>
		<?php 
		  foreach ($peer_reviewers->peer_reviewer_tab as $name => $function):
			$color = ($line_counter++ % 2 == 0)? "rouge" : "vert";
			?>				  
			 <tr class="<?= $color ?>">
			 <td colspan="3"><?= $name ?></td>
			 <td colspan="3"><?= $function ?></td>
			 <td><?= $peer_reviewers->peer_reviewer_nb_tab[$name] ?></td>
			 </tr>
		  <? endforeach?>
		</tbody>
		</table>
		</div>
		<div class="spacer"></div>
		</div>			
</div> 
