<img class="bar" src="<?= $bar_filename ?>" alt="Remarks graph" style="float:right" />
<img class="pie" src="<?= $pie_filename ?>" alt="Peer reviewers graph" />
<div class="spacer"></div>
<?= $html ?>
<form id="import_prr" name="import_prr" method="POST" action="<?= Atomik::url('peer_review/import_prr')?>" enctype="multipart/form-data">
<fieldset>
<input type="hidden" name="type_remark" value="<?= $type_remark ?>"/>
<input type="hidden" name="format_remark" value="<?= $type ?>"/>
<input type="hidden" name="filename" value="<?= $uploadName ?>"/>
<input type="hidden" name="filesize" value="<?= $uploadSize ?>"/>
<input type="hidden" name="data" value="<?= $application ?>"/>
<input type="hidden" name="remark_date" value="<?= $date_dojo ?>"/>
<input type="hidden" name="nb_remarks" value="<?= $nb_remarks ?>"/>
<span class="art-button-wrapper">
<span class="l"> </span>
<span class="r"> </span>
<input class="art-button" name="submit_import" type="submit" value="Import" ></span>
<span class="art-button-wrapper">
<span class="l"> </span>
<span class="r"> </span>
<input class="art-button" name="submit_cancel" type="submit" value="Cancel"></span>
</fieldset>
</form>
<table cellspacing="0" class="pagetable">
<thead>
<tr>
<? foreach( $header_fields as $value => $colpsan):?>
	<th colspan="<?= $colpsan ?>"><?= $value?></th>
<? endforeach ?>		
</tr>
</thead>	
<tbody>	
<?php 
if ($list_remarks != null){
	foreach ($list_remarks as $row):
		$color = ($line_counter++ % 2 == 0)? "rouge" : "vert";
		$color_found = ($row['qams_id'] !== false)? "green" : "";
		$color_author = ($row['poster_id'] !="")? "green" : "orange";
		$color_paragraph = ($row['paragraph_check'])? "" : "yellow";
		$color_response = ($row['response_check'])? "" : "yellow";
		$color_description = ($row['description_check'])? "" : "orange";
		?>
		<tr class="<?= $color?>">	
		<td><?= $row['id'] ?></td>
		<td colspan="2" class="<?= $color_author?>" ><?= $row['author'] ?></td>
		<td colspan="2" class="<?= $color_paragraph ?>"><?= $row['paragraph'] ?></td>
		<td colspan="2"><?= $row['line'] ?></td>
		<td colspan="4" class="<?= $color_description ?>"><?= $row['description'] ?></td>
		<td colspan="4" class="<?= $color_response ?>"><?= $row['author_response'] ?></td>
		<td colspan="2"><?= $row['defect_class'] ?></td>
		<td colspan="2"><?= $row['status'] ?></td>
		<td colspan="2"><?= $row['justification'] ?></td>
		<td  class="<?= $color_found?>"><?= $row['qams_id'] ?></td>
		</tr>
	<?php 
		// if ($line_counter == 13){
			// var_dump($row['description']);
			// $text = Tool::convert2ascii($row['description']);
			// var_dump($text);
			// $search = array ('/[\x80-\xFF]/');
			// $replace = array ('&nbsp;');
			// $result = preg_replace($search, $replace, $row['description']);	
			// var_dump($result);
			// exit();
		// }	
	
	endforeach; 
}
?>
</tbody>
</table>
