<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=7">
		<link rel="shortcut icon" href="/qams/qams.ico" />
        <title>Remark workflow</title>
        <link rel="stylesheet" type="text/css" href="/qams/atomik/assets/css/main.css" />
	</head>
	<body>
	<form method="POST" name="status_form" action="change_remarks_status.php">
	<select class='combobox' onchange="status_form.submit()" name='status_id' >
	<option value=''>--All--
	<?php foreach ($status_list as $row) {
		/* status type */
		print "<option value='{$row['id']}'";
		if ($row['id'] == $status_id) {
			print " SELECTED";
		}
		print ">{$row['name']}";
	}?>
	</select>
	<input type="hidden" name="remark_id"  value="<?php echo $remark_id ?>"/>
	</form>
	<?= $diagram_img ?>
	<?= $error ?>
	<script type="text/javascript" src="assets/js/libs/data.js"></script>
	</body>
</body>