<div class="nice_square go_right">
  <div id="project_front_page_id" class="user_guide"
  style="min-height:600px;padding-top:10px">
    <div class="image_board" style="opacity:1">
	<div style='color:#FFF;background-color:#000;min-height:680px;width:590px;margin-left:20px;opacity:0.7;padding-top:10px;padding-right:10px;overflow:scroll'>
      <div class="image_board_text_about">
      <div class="user_guide" style="float:right">
        <p>Tool to manage quality assurance artifacts:</p>
        <ul>
          <li>Data status tracking</li>
          <li>Peer reviews tracking</li>
          <li>Action items tracking</li>
          <li>Milestone meeting reviews</li>
        </ul>
      </div>	  
      <b>Q</b>uality 
      <br />
      <b>A</b>ssurance 
      <br />
      <b>M</b>anagement 
      <br />
      <b>S</b>ystem 
	  <div class="spacer"></div>
	  <p style_="float:right">Written by <a href="edit_user?edit_user_id=1">Olivier App&eacute;r&eacute;.</a></p>
	  <pre style="color:#000">
	The following software is required to run QAMS
	.	PHP version 5.2.0 or newer but not compatible with 5.3
	.	PHP extension php_zip enabled
	.	PHP extension php_xml enabled
	.	PHP extension php_gd2 enabled (if not compiled in)
	.	PHP extension mysql
	.	MySQL client version 5.0.51a or newer
	 </pre>	  
      <p>Here is the list of different projects used to create this
      application:</p>
      <ul>
        <li>
        <a href="http://atomikframework.com">Atomik
        Framework</a> version 2.2<p class="small_font">Atomik is a PHP micro framework</p></li>
        <li>
        <a href="http://phpword.codeplex.com">PHPWord</a> version
        Beta 0.6.2, 24.07.2010<p class="small_font">PHPWord is a library written in PHP that create word documents. </p></li>
        <li>
        <a href="http://phpexcel.codeplex.com/">PHPExcel</a> version
        1.7.6<p class="small_font">PHPExcel is a library written in PHP that create excel documents. </p></li>
        <li>
        <a href="http://www.tcpdf.org/">TCPDF</a> version
        6.0.010<p class="small_font">TCPDF is a FLOSS PHP class for generating PDF documents</p></li>
        <li>
        <a href="">pChart</a> version
        2.1.3<p class="small_font">pChart is a PHP class oriented framework designed to create anti-aliased charts.</p></li>
        <li>
        <a href="http://ckeditor.com/">CKEditor</a> version
        3.2<p class="small_font">CKEditor is a ready-for-use HTML text editor designed to simplify web content creation. It's a WYSIWYG editor that brings common word processor features directly to your web pages.</p></li>		
      </ul>
	  </div>
    </div>
	</div>
  </div>
</div>

