<div class="nice_square go_right">
<form action="" method="post" name="my_form" >
	<fieldset>
	Title:<br/>
	<input type="text" style="width:500px" name="titre" value="<?= $post->getTitle() ?>"/><br/>
	Content:<br/>
	<textarea class="ckeditor" cols="80" id="description" name="texte" rows="10" ><?= $post->getDescription() ?></textarea>
	<span class="art-button-wrapper" >
		<span class="l"> </span>
		<span class="r"> </span>
		<input class="art-button" type="submit" value="<?= $button ?>"/>
	</span>
	<span class="art-button-wrapper" >
		<span class="l"> </span>
		<span class="r"> </span>
		<input class="art-button" type="submit" name="submit_cancel" value="Cancel"/>
	</span>	
	<input type="hidden" name='chapo' value="<?= $Id_User ?>">
	<input type="hidden" name='update' value="<?= $update ?>"/>
	<input type="hidden" name='update_id' value="<?= $update_id ?>"/>
	</fieldset>
</form>
</div>
<script type="text/javascript">
	CKEDITOR.replace( 'description',
	{	
		toolbarStartupExpanded : false,
		height : '1000',
		width : '800'
	});
</script>