<div class="nice_square go_right">
<!--
<a href="<?= A('filename') ?>" >
<img alt="Export openxml" title="Export openxml" border=0 src="assets/images/128x128/120px-OfficeWord.png" class='img_button' />
</a> 
-->
<div class="<?= A('css_display') ?>">
<!-- <iframe name="get_word_memo" width="280" style="witdh:160px;height:400px;border:none"></iframe> -->
<form class='post_' name='create_memo' action='' method='post'>
    <fieldset class="medium">
		<label for='reference'>Reference:</label>
        <textarea cols="60" rows="1" name='reference' ><?= A('reference') ?></textarea><br />
		<label for='subject'>Subject:</label>
        <textarea cols="60" rows="1" name='subject' ></textarea><br />
        <label for='description'>Body</h3></label>
        <div style="float:left">
        <textarea class="ckeditor" cols="50" id="description" name="description" rows="10"></textarea>
        </div>

        <input type="hidden" name='memo_id' value='<?= A('memo_id') ?>' />
    </fieldset>
            <span class="art-button-wrapper">
            <span class="l"> </span>
            <span class="r"> </span>
            <label for='button' style='padding: 0 0 0 0'></label>	
			<input class="art-button" type="submit" value="Create memo" name="button" />
		</span>
</form>
</div>
</div>
<script type="text/javascript">
	CKEDITOR.replace( 'description',
	{	
		toolbarStartupExpanded : true,
		height : '400',
		width : '700'
	});
</script>	
