<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>No database</title>
	<link rel="shortcut icon" href="/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="assets/css/style_login.css" />
</head>
<body>
<form method='POST' action="<? Atomik::url('create_db')?>">
<p style="margin-top:200px">No valid database are available. Click on the button below to instanciate a QAMS database.</p>
<span class='art-button-wrapper'>
<span class='l'> </span>
<span class='r'> </span>
<input class='art-button' type='submit' name="create_db" value='Create database'>
</span>
</form>
</body>
</html>