<div id="page_tabs">
<div id="data_description" class="<?= A('description_highlight')?>">Description</div>
<div id="attendees" class="<?= A('attendee_highlight')?>">Attendees</div>
</div><!-- EndTabHeaders -->
<div class="clearb"></div>
<div class="nice_square go_right">
<div id="data_description_c">
<!--
<a href="<?= A('filename') ?>" >
<img alt="Export openxml" title="Export openxml" border=0 src="assets/images/128x128/120px-OfficeWord.png" class='img_button' />
</a> 
-->
<div class="<?= A('css_display') ?>">
<!-- <iframe name="get_word_memo" width="280" style="witdh:160px;height:400px;border:none"></iframe> -->
<form class='post_' name='create_memo' action='' method='post'>
    <fieldset class="medium">
		<label for='reference'>Reference:</label>
        <textarea cols="60" rows="1" name='reference' ><?= A('reference') ?></textarea><br />
		<label for='subject'>Subject:</label>
        <textarea cols="60" rows="1" name='subject' ></textarea><br />
        <label for='description'>Body</h3></label>
        <div style="float:left">
        <textarea class="ckeditor" cols="50" id="description" name="description" rows="10"></textarea>
        </div>

        <input type="hidden" name='memo_id' value='<?= A('memo_id') ?>' />
    </fieldset>
            <span class="art-button-wrapper">
            <span class="l"> </span>
            <span class="r"> </span>
            <label for='button' style='padding: 0 0 0 0'></label>	
			<input class="art-button" type="submit" value="Create memo" name="button" />
		</span>
</form>
</div>
</div>
<div id="attendees_c">
<h2>List of attendees</h2>
<? if ($review->id != ""){
if ($review->attendees != null) {?>
	<table cellspacing="0" class="pagetable" style="float:left;width:70%">
	<thead><tr><th>Company</th><th colspan="2">Attendee</th></tr></thead>
	<tbody>
    <? foreach( $review->attendees as $id => $users ):
			$color = ($line_counter++ % 2 == 0) ? "rouge" : "vert";?>
			<tr class='<?= $color?>' style='color:#74A8C4'><td><?= $users['company']?></td><td colspan="2">
			<b><a href="<?=Atomik::url('edit_user',array('id'=>$users['id']))?>"><?= $users['lname']." ".$users['fname']?></a></b> <?= $users['function']?>
			<a href='<?= Atomik::url('remove_review_assign',array('id'=>$users['link_id']))?>' >
			<img style='padding-left:5px;padding-top:5px' border='0' width='20' height='20' src='<?= Atomik::asset('assets/images/32x32/agt_action_fail.png')?>' alt='remove link' title='remove link' /></a><br/>
			</td></tr>
	<?endforeach?>
    </tbody>
   </table>
<? 
}?>
<div class="spacer"></div>
<h2>List of persons to be informed</h2><br/>
<?php if ($review->person_copy != null) {?>
	<table cellspacing="0" class="pagetable" style="float:left;width:50%">
	<thead><tr><th>Company</th><th colspan="2">Attendee</th></tr></thead>
	<tbody>
    <? foreach( $review->person_copy as $id => $users ):
			$color = ($line_counter++ % 2 == 0) ? "rouge" : "vert";?>
			<tr class='<?= $color?>' style='color:#74A8C4'><td><?= $users['company']?></td><td colspan="2">
			<b><?= $users['lname']." ".$users['fname']?></b> <?= $users['function']?>
			<a href='<?= Atomik::url('remove_review_assign',array('id'=>$users['link_id']))?>' >
			<img style='padding-left:5px;padding-top:5px' border='0' width='20' height='20' src='<?= Atomik::asset('assets/images/32x32/agt_action_fail.png')?>' alt='remove link' title='remove link' /></a><br/>
			</td></tr>
		<?endforeach?>
    </tbody>
    </table>
  <?	
  }
}?>  
<div class="spacer"></div>
<form method='post' action="<?= Atomik::url('review/add_user_review_link')?>">
<fieldset class="no_medium_black">
<label for='project' style='color:#74A8C4'>Add a person</label>
<select  class='combobox' name='users_id' >
<option value=''>--All--
<?php
foreach ($project->getUsers($review->project_id) as $row) {
	print "<option value='{$row['id']}'";
	/*if ($row['id'] == $add_app_author) {
		print " SELECTED";
	}*/
	print ">{$row['lname']} {$row['fname']}";
}?>
</select>
Copy:
<input type="checkbox" name="copy" id="copy" VALUE="on"/>
<br />
<span class="art-button-wrapper">
<span class="l"> </span>
<span class="r"> </span>
<input class='art-button' type='submit' value='Add person'>
</span>
</fieldset>
</form>

</div>
</div>
<script type="text/javascript">
	cms_page_tab_style();
	CKEDITOR.replace( 'description',
	{	
		toolbarStartupExpanded : true,
		height : '400',
		width : '700'
	});
</script>	
