<div class="nice_square go_right">
<form action="" method="POST" name="my_form2" >
	<h2><?= A('sub_title')?></h2>
	<fieldset>
	<label for='item_order'>Item</label>
	<input type='text' name='item_order' value='<?= $item_no?>' id='item_order'><br/>	
	<label for='tag'>Tag</label>
	<input type='text' name='tag' value='<?= $question->tag?>' id='tag'><br/>		
	<textarea class="ckeditor"cols="<?= $input_width ?>" id="question" name="question" rows="1" ><?= $question->text?></textarea>			
	<dl><dd style="padding-left:0px">
		<span class="art-button-wrapper" >
			<span class="l"> </span>
			<span class="r"> </span>
			<input class="art-button" type="submit" name="add_submit" id="add_submit" value="<?= A('button')?>"/>
		</span>
		<span class="art-button-wrapper" >
			<span class="l"> </span>
			<span class="r"> </span>
			<input class="art-button" type="submit" name="submit_cancel_2" id="submit_cancel_2" value="Cancel"/>
		</span>				
	</dd>
</dl>
</fieldset>
<input type="hidden" name="question_id" value="<?= $question->id?>">
<input type="hidden" name="review_id" value="<?= $update_id?>">
</form>	
<form action="" method="POST" name="my_form" >
<fieldset>
<? if ($nb_questions > 0) {
?>
<h2>Current questions</h2>
	<? foreach ($questions_array as $row):?>		
	<textarea class="ckeditor"cols="<?= $input_width ?>" id="question<?= $row['id']?>" name="question_<?= $row['id']?>" rows="1" ><?= $row['question'] ?></textarea>
	<? endforeach?>
	<dl><dd style="padding-left:0px">
		<span class="art-button-wrapper" >
			<span class="l"> </span>
			<span class="r"> </span>
			<input class="art-button" type="submit" id="update_submit" value="Update"/>
		</span>	
		<span class="art-button-wrapper" >
			<span class="l"> </span>
			<span class="r"> </span>
			<input class="art-button" type="submit" name="submit_cancel_1" id="submit_cancel_1" value="Cancel"/>
		</span>					
	</dd>
</dl>		
<? 
} ?>		
</fieldset>
</form>

</div>
<script type="text/javascript">
//<![CDATA[
	CKEDITOR.replace( 'question',
	{	
		toolbarStartupExpanded : true,
		height : '200',
		width : '800'
	});
	CKEDITOR.replace( 'new_question',
	{	
		toolbarStartupExpanded : true,
		height : '200',
		width : '800'
	});	
//]]>
</script>	
