<div class="nice_square go_right">
<div style="float:right;margin-right:40px;padding:10px">
<img src="<?= $project->photo_file ?>" alt="" width="200" >
	<div class="<?= A('css_modify')?>">
	<p><a href="#" style="text-decoration: none;outline-width: medium;outline-style: none;" title="Add a picture">
	<img src="<?= Atomik::asset('assets/images/newobject.gif')?>" class="systemicon" width="36" height="32" alt="Add a picture" title="Add a picture" border="no" onclick="new_picture_form.submit()"/> Add a picture</a></p>
	<form method="post" action="<?= Atomik::url('edit_project')?>" enctype="multipart/form-data" id="new_picture_form" name="new_picture_form" >   
		<fieldset>
		<input type="hidden" name="MAX_FILE_SIZE" value="30000000">   
		<input type="file" style="width:300px" name="filename" >
		<input type="hidden" value='<?= $project->id ?>' name='user_id' />
		<input type="hidden" value='yes' name='upload_data' /><br/>
		<span class="art-button-wrapper">
		<span class="l"> </span>
		<span class="r"> </span>
		</fieldset>
	</form>
	</div>
</div>
<div style="margin:10px;width:400px">
<form method='POST' action="<?= Atomik::url('edit_eqpt', false) ?>">
<fieldset class="medium">
<label for='aircraft_id'>Aircraft:</label>           
<select class='combobox' onchange_="this.form.submit()" name='aircraft_id'>
<option value=''/> --All--
<? foreach($list_aircraft as $row):?>
    <option value="<?= $row['id'] ?>"
    <? if ($row['id'] == $project->aircraft_id){ print " SELECTED ";}?>
    ><?= $row['aircraft']?>
<? endforeach ?>
</select><br /> 
<label for='project_id'>System:</label>           
<select class='combobox' onchange_="this.form.submit()" name='project_id'>
<option value=''/> --All--
<? foreach($list_projects as $row):?>
    <option value="<?= $row['id'] ?>"
    <?php if ($row['id'] == $project->getProjectId()){ print " SELECTED ";}?>
    ><?= $row['project']?>
<? endforeach ?>
</select><br />
<?= $list_items ?><br/>
<label>Name:</label>    
<input type='text' name='name' value='<?= $project->getSubProjectName() ?>' id='name'><br/>
<label>PN:</label>
<input type='text' name='part_number' value='<?= $project->part_number ?>' id='part_number'><br/>
<label>DAL:</label>
<select class='combobox' onchange_="this.form.submit()" name='dal'>
<? foreach(array(1=>"A",2=>"B",3=>"C",4=>"D",5=>"E") as $key => $dal):?>
<option value="<?= $dal ?>"<? if ($dal == $project->dal){ print " SELECTED ";}?>><?= $dal?>
<? endforeach ?>
</select><br />
<label>Scope:</label>
<select class='combobox' onchange_="this.form.submit()" name='scope_id'>
<? foreach(array(1=>"System",2=>"Software",3=>"Hardware",4=>"Equipment") as $scope_id => $scope_name):?>
<option value="<?= $scope_id ?>"<? if ($scope_name == $project->scope){ print " SELECTED ";}?>><?= $scope_name?>
<? endforeach ?>
</select><br />
<?= User::getSelectAssignee(&$project,$project->manager_id) ?><br/>
<b>Description:</b>
<textarea class="ckedito" cols="50" id="description" name="description" rows="5" style="300px"><?= $project->description ?></textarea><br/>
<b>Abstract:</b>
<textarea class="ckeditor" cols="60" id="abstract" name="abstract" rows="5" ><?= $project->abstract ?></textarea><br/>
</fieldset>
<input type='hidden' name='id' value='<?= $id?>'/>
<input type='hidden' name='page' value="<?= $page?>">
<input type='hidden' name='limite' value="<?= $limite?>">
<span class="<?= A('css_admin')?>">
<span class="art-button-wrapper ">
<span class="l"> </span>
<span class="r"> </span>
<input class='art-button' type='submit' name="<?= $submit?>" value='<?= $button?>'>
</span>
</span>
<span class="art-button-wrapper">
<span class="l"> </span>
<span class="r"> </span>
<label for='button' style='padding: 0 0 0 0'></label>
<input class="art-button" type="submit" value="Back" name="cancel" />
</span>	
</form>
</div>
<iframe id="uploadFrame" name="uploadFrame" src="#" style="display:none"></iframe>
<span id="export_data_list_frame"></span>
</div>
</div>
<script type="text/javascript">
//<![CDATA[
    CKEDITOR.replace( 'abstract',
    {   
        toolbarStartupExpanded : false,
        height : '200',
        width : '450'
    });   
//]]>
</script>