<div class="nice_square go_right">
<table cellspacing="0" class="pagetable" style="width:812px">
<thead>
<tr><th colspan="4"></th></tr>
</thead> 
<tbody> 
<?php 
foreach ($list_data as $row) {
	$table_color= ($fill)?'rouge':'vert';?>
	<tr class="<?= $table_color ?>">
    <td style="padding:10px"><img src="<?= $row['thumbnail']?>" width="200"></td>
	<td style="padding:10px"><a href="<?= Atomik::url('edit_aircraft',array('id'=> $row['id']))?>"><?= $row['company']." ".$row['aircraft'] ?></a></td><td></td><td> 
         <a style="float:right"><span class='down_arrow' style="margin-left:0px" onClick="return display_action_comment('systems_<?= $row['id'] ?>',this)"></span></a><br/>
	</td>
        </tr>
	<tr class="menu" id="systems_<?= $row['id']?>" >
	<td colspan="3" style="padding:20px"><?= $row['description'] ?>
	<? $list_systems = Aircraft::getSystems($row['id']);
	foreach ($list_systems as $row2):
		echo "<b>".$row2['system']."</b>: ".Tool::clean_text($row2['description'])."<br/>";
	endforeach;
	?>
	</td>
	</tr> 	
    <?php
	$fill=!$fill;
}
?>
</tbody> 
</table>
</div>
