<div class="nice_square go_right">
<table cellspacing="0" class="pagetable" style="width:812px">
<thead>
<tr><th colspan="3">Type</th><th colspan="7">Description</th></tr>
</thead> 
<tbody> 
<?php 
foreach ($list_type as $row) {
	$color = ($fill) ? "rouge" : "vert";?>
	<tr class="<?= $color ?>">
	<td colspan="3"><a href="<?=Atomik::url('edit_review_type',array('id'=>$row['id']))?>"><?= $row['name']." ".$row['type'] ?></a></td>
	<td colspan="6"><?= $row['description'] ?></td>
	<td><a style="float:right"><span class='down_arrow' style="margin-left:0px" onClick="return display_action_comment('do178b_data_<?= $row['id'] ?>',this)"></span></a><br/>
	</td>
    </tr>
	<tr class="menu" id="do178b_data_<?= $row['id'] ?>" >
	<td colspan="10">
	<h3>Objectives</h3>
	<blockquote>
	<?= $row['objectives'] ?>
	</blockquote>
	</td>
	</tr> 	
 <?php
	$fill=!$fill;
}
?>
</tbody> 
</table>
</div>
