<div class="nice_square go_right">
<table cellspacing="0" class="pagetable">
    <thead>
        <tr class='vert' >
            <? /* foreach ($header_fields as $value ): */?>
            <th colspan="2">Id</th><th colspan="2">Checklist</th><th colspan="2">Item</th><th colspan="11">Question</th>
            </th>
            <? /* endforeach */?>
        </tr>
    </thead>
    <tbody>
        <? 
         foreach ($questions as $row_table):
         	$color = ($fill) ? "rouge" : "vert";?>
        	<tr class="<?=$color?>">	
            <td colspan="2"><a href="<?= Atomik::url('edit_checklist', array('question_id' => $row_table['id']))?>"><?= $row_table['acronym']."_"?><? printf("%1$03d",$row_table['item_order'])?></a></td>
            <td colspan="2"><?= $row_table['description'] ?></td>
            <td colspan="2"><?= $row_table['tag'] ?></td>
            <td colspan="10"><?= $row_table['question'] ?></td>
			<td><a style="float:right" href='<?= Atomik::url('remove_question', array('id' => $row_table['id'],'review_id' => $checklist_id))?>' >
			<img style='padding-left:5px;padding-top:5px' border=0 width='20' height='20' src='assets/images/32x32/agt_action_fail.png' alt='remove link' title='remove link' /></a></td>
        </tr>
        <? $fill = !$fill;endforeach?>
    </tbody>
</table>
</div>
<?php Atomik::flash(A('nb_entries')." entries found", 'success'); ?>