<div class="nice_square go_right" style="background-color:#F8F8F8">
<div id="page_tabs">
<div id="meetings">Meetings</div>
<div id="export">Export</div>
</div><!-- EndTabHeaders -->
<div class="clearb"></div>
<div id="meetings_c">
<form name="orderform" action="#" >
	<? foreach ($review_list as $events):
		$review->get($events['id']);
	?>
	<li class="alt"  id="comment-217" style="list-style-type:none">
	  <div class="event_descr_ review_nice_square" style='margin-left:0px;margin-top:18px;padding-bottom:5px;background-color:#FFF'>
		<div style="float:left"><h2><input  type='checkbox' class='styled' name='modify_action_id' value="<?= $review->id?>">
		<?= $events['company']." ".$events['type_description']." ".$review->project." ".$review->lru ?> </h2>
	  	<small class="commentmetadata">
		  <img class='calendar' src="" alt=""/><?= $review->getPerfomedOn() ?>
		  <? echo ($review->managed_by !="") ?'by '.$review->managed_by:""?>
		 </small>
		</div>		 
		<div class='eg-image_' style="margin-left:400px">
		<a href="<?= Atomik::url('post_review',array('id' => $review->id)) ?>">
		  <img class='button' src="<?= Atomik::asset('assets/images/32x32/edit.png')?>" alt="doc" title="Edit Review"/>Edit review</a>
		<a href="<?= Atomik::url('export/export_docx_review_template',array('id' => $review->id)) ?>">
		  <img class='button' src="<?= Atomik::asset('assets/images/32x32/OfficeWord.png')?>" alt="doc" title="Edit Review"/>Export minutes</a>		  
		<a href="#" onclick="send_minutes(<?= $events['id']?>)">
		<img class='button' alt="Send MoM" title="Send MoM" src="<?= Atomik::asset('assets/images/32x32/mail_send.png')?>" />Send Minutes</a>		  
		  <? $review_id = 'review_'.$review->id?>
		</div>
			<div class="spacer"></div>
		  <p><h3>Objective:</h3> 
		  <blockquote style="min-height:100px">
		  <?= $events['objective'] ?>
		  </blockquote>
		  </p>
		  <p>Status: <?= $review->getStatus() ?>
		  <a style="float:right;margin-right:20px"><span class='down_arrow' style='margin-left:10px' onClick="return display_atomik_review('<?= $review_id ?>',this)"></a></p>
		  <div class='menu' id="<?= "review_".$events['id'] ?>" >
		  <p>
		  <?php
	  if ($review->link != "empty") {
		  ?>
		  <br/> Report:
		  <a href="<?php echo $review-> link ?>">
			<img alt="Document attached" title="Document attached" width="16" height="16" border="0" src="<?= $review->link_mime ?>" /></a>
			<a href="<?= Atomik::url('edit_data',array('id'=>$review-> report_link_id))?>"><?= $review->reference ?></a>
		<?php
		}
		else if ($review-> reference != ""){
			echo "<br/> Report: ";
	?> 
	<a href="<?= Atomik::url('edit_data',array('id'=>$review-> report_link_id))?>"><?= $review->reference ?></a>
	<?php
		}
		else {
		   echo "";
		  }?>
		  </p>
		  <h2>Attendees</h2>
		  <table class="art-article pagetable" >
		  <thead>
		  <tr><th>Name</th><th>Company</th><th>Function</th></tr>
		  </thead>
		  <tbody>
		  <? foreach ($review->attendees  as $attendee):
		  $color = ($fill)?'rouge':'vert';
		  ?>
			<tr class="<?=$color?>">
			<td><?=$attendee['fname']." ".$attendee['lname']?></td>
			<td><?=$attendee['company']?></td>
			<td><?=$attendee['function']?></td>
			</tr>
		  <? $fill = !$fill;
		  endforeach?>
		 </tbody>
		  </table>
		  <div >
		  <h2>Description</h2>
		  <blockquote style="min-height:100px">
		<?php 
		$descr = $events['description'];
		$description = html_entity_decode ($descr,ENT_QUOTES,"UTF-8");
		$longueur = strlen(strip_tags($description));
		if ($longueur < 3)$description = $events['objectives'];	?>
		  <?= $description ?>
		  <br/>
		  <br/>
		  </blockquote>
		  <h2>Conclusion</h2>
		  <blockquote style="min-height:100px">
		<?= $events['comment']?>
		</blockquote>
		</div></div>
	  </div>
	  <div style="height:20px;">
	  </div></li>
	<? endforeach; ?>
	<?php if ($count_review == 0){?>
	<li class='warning' style='list-style-type: none;margin-top:40px;margin-right:10px'>
		No review meeting recorded so far for this project.
		</li>
	<?}
	?>
</form>
</div>
<div id="export_c">
<div class="subnav">
<h1 >Export Minutes</h1>
</div>  		
	<div class="my_menu" style="width:600px">
	<br/><p>Select minutes to generate by checking checkbox in <b>Meetings</b> folder.</p>
	<ul>   
		<li class="export_word"><h2><a href="#" onclick="return review_word_get_checkbox_value();" border="0" >MoM basic</a></h2></li>
		<li class="export_word"><h2><a href="#" onclick="return review_full_word_get_checkbox_value();" border="0" >Full MoM Word</a></h2></li>
		<li class="export_excel"><h2><a href="#" onclick="return review_excel_get_checkbox_value();" border="0" >Full MoM Excel</a></h2></li>
		<li class="export_pdf"><h2><a href="#" onclick="return review_html_get_checkbox_value('display');" border="0" >Display MoM html</a></h2></li>
		<li class="email"><h2><a href="#" onclick="return review_html_get_checkbox_value();" border="0" >Mail MoM html</a></h2></li>
	</ul>
  </div>  
</div>
</div>
</div>
<script type="text/javascript" src="../coloration/scripts/shCore.js" ></script>
<script type="text/javascript" src="../coloration/scripts/shBrushAsm.js" ></script>
<script type="text/javascript" src="../coloration/scripts/shBrushCpp.js" ></script>
<script type="text/javascript" src="../coloration/scripts/shBrushPerl.js" ></script>
<script type="text/javascript">
 /* SyntaxHighlighter.all(); */
 cms_page_tab_style()
</script>