<div id="page_tabs">
<div id="users" class="active">Users</div>
<div id="export">Export</div>
</div><!-- EndTabHeaders -->
<div class="clearb"></div>
<div class="nice_square go_right">
<div id="users_c">
<div>
<ul class="little_boxes">
<li><a  href="<?= Atomik::url('users',array('show_letter'=>""))?>"></a></li>
<?php
for ($i=ord("A");$i<=ord("Z");$i++)
   {
	  $letter = chr($i);
	  if ($filter_letter == $letter){
		$active_letter="letter_select";
	  }
	  else {
	  	$active_letter="";
	  }
	  ?>
	  <li>
	  <a  href="<?= Atomik::url('users',array('show_letter'=>$letter))?>" class="<?= $active_letter ?>"><?= $letter?></a></li>
	  <?php
   }
?>
</ul>
</div><br/>
<table cellspacing="0" class="pagetable" style="width:824px;">
<thead>
<tr class='vert'>
<th colspan="4">Name</th><th colspan="2">Company</th><th colspan="2">Function</th><th colspan="5">Project</th><th>Email</th><th colspan="3">Telephone</th>
</tr>
</thead><?php
if ($nbtotal != 0){ 
	foreach ($list_users_lite as $row) {
		$user->get_user_info($row['id']);
		$color = ($line++ % 2 == 0) ? 'rouge' : 'vert';
		if (!$user->getActive()){
			$color = 'rouge_fonce';
		}
		?>
		<tr class='grey_border <?= $color?>'>
		<td colspan="2"><img src="<?= $user->thumbnail?>" width="48"></td>
		<td colspan="2"><?= $user->name ?></td>
		<td colspan="2"><?= $user->company_name ?></td>
		<td colspan="2"><?= $user->user_function ?></td>
		<td colspan="5">
		<?
		if ($user->projects != null) {
		  ?><ul><?
		  foreach ($user->projects as $row) {
			echo "<li>".$row['aircraft']." ".$row['project']."</li>";
		  }
		  ?></ul><?
		}
		?>
		</td>
		<td>
		<?php if ($user->email != "") { ?>
		<a href="mailto:<?= $user->email?>">
		<img alt="Send mail" title="Send mail" border="0" src="assets/images/64x64/xfmail.png" height="24" width="24" />
		</a>
		<?php } ?>
		</td>
		<td><?= $user->phone ?></td>
		<td colspan="2">
		<? if(User::getAdminUserLogged()){
			?>
			<form method='POST' action="<?= Atomik::url('edit_user')?>">
			<input type='hidden' name='edit_user_id' value="<?= $user->id ?>">
			<input type='hidden' name='page' value="<?= $page?>">
			<input type='hidden' name='limite' value="<?= $limite?>">
			<span class="<? A('css_admin')?>">
			<span class="art-button-wrapper">
			<span class="l"> </span>
			<span class="r"> </span>
			<input class='art-button' type='submit' value='Edit'>
			</span></span>
			</form>
		<?}
		?>
		</td></tr>
		
	<? }	
}?>
</table>
</div>
<div id="export_c">
<form method ="POST" action "<?= Atomik::url('users',false)?>">
<span class="art-button-wrapper">
<span class="l"> </span>
<span class="r"> </span>
<input class='art-button' type='submit' name="export_user_submit" value='Export'>
</span>
</form>
</div>
</div>
</div>
<?php Atomik::flash(A('nb_entries')." entries found", 'success'); ?>
<script type="text/javascript">
cms_page_tab_style();
</script>