<div id="user_guide_c">
<div class="nice_square" style="float:right">
<h1><img src="<?= Atomik::asset('assets/images/64x64/tutorials.png')?>" class='img_button' >QAMS User's guide</h1><hr>
<p><a href="#" onclick="get_user_guide('../users_guide/user_guide_fr.php');return false;">Fr</a>/<a href="#" onclick="get_user_guide('../users_guide/user_guide.php');return false;">En</a><a href="../users_guide/outil_dev_workflow_pres.pdf"><img alt="export pdf" title="export pd" width="16" height="16" border="0" src="<?= Atomik::asset('assets/images/pdficon_large.gif')?>" /></a></p>
<p id="user_guide_page"></p>
</div>
<div class="spacer"></div></div>
<script type="text/javascript">
	get_user_guide('../users_guide/user_guide_fr.php');
	cms_page_tab_style();
	/* dojo.require("dojo.data.ItemFileReadStore"); */
	/* dojo.require("dojox.image.Gallery"); */ /* For gallery */
	/* dojo.require("dojox.image.SlideShow"); */ /* For slideshow */
</script>
