<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
<!-- <link rel="stylesheet" href="../style.css" type="text/css" media="screen" /> -->
<!-- <link rel="stylesheet" type="text/css" href="../users_guide/user_guide.css" /> -->
<link href="../coloration/styles/shCore.css" rel="stylesheet" type="text/css" media="screen" />
<link href="../coloration/styles/shThemeDefault.css" rel="stylesheet" type="text/css" media="screen" />
<!--[if IE 6]><link rel="stylesheet" href="style.ie6.css" type="text/css" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="style.ie7.css" type="text/css" media="screen" /><![endif]-->
<style type="text/css">
/* @import url('../style.css'); */
@import url('../coloration/styles/shCore.css');
@import url('../coloration/styles/shThemeDefault.css');
@import url('../atomik/assets/css/main.css');
/* @import url('../atomik/assets/css/home.css'); */
@media print
h1,h2 {page-break-before:always}

h1, h2 
{
	margin-top: 0.25em;
	margin-right: 0pt;
	margin-bottom: 0.25em;
	margin-left: 0pt;
	font-family: "Century Gothic","Trebuchet MS",Helvetica,Arial,Geneva,sans-serif;
	font-style: normal;
	font-variant: normal;
	font-weight: normal;
	font-size: 1.2em;
	line-height: 1.1;
	font-size-adjust: none;
	font-stretch: normal;
	-x-system-font: none;
	letter-spacing: 1px;

}
h1 {
	padding-top:40px;
}
/* bandeau and piedpage should not be used for IE6. IE6 does not understand html>body */
html>body div#bandeau {
	/* float:left; */
	/* width:12%; */
	height:390px;
	/* margin-left:40px; */
	background-color:#FFFFFF;
	background-image: url('../assets/images/saq_086_header.jpg');
	background-repeat: no-repeat;
	}	
html>body div#piedpage {
	/* width:1024px; */
	height:68px;
	background-color:#FFF;
	background: url("../assets/images/mastering_the_elements_1124.jpg") no-repeat left top;
	clear:both;
	z-index:1;
	}
div#zodiac_background {
	position:relative;
	background-image: url("../users_guide/images/zodiac_ppt_last_page.jpg");
	background-repeat: no-repeat;
	opacity:1;
}	
div#zodiac_openspace {
	position:relative;
	margin-left:50px;
	background-image: url("../users_guide/images/openspace.jpg");
	background-repeat: no-repeat;
	opacity:0.5;
	filter : alpha(opacity=50);
	height:307px;
}	
div#context_background {
	position:relative;
	margin-left:50px;
	padding-top:740px;
	background-image: url("../users_guide/images/qams_global_process.jpg");
	background-repeat: no-repeat;
	opacity:0.5;
	filter : alpha(opacity=50);
	/* height:800px; */
}	
body {
	background-color:#FFF;
}	
div.sub_body  {
	width:1124px;
	background-color:#FFF;
}
p{
	margin-left:20px;
	margin-right:20px;
}
img{
	margin-left:5px;
	margin-right:5px;
}
div#sommaire_black {
	color:#FFF;
	background-color:#000;
	height:620px;
	width:340px;
	padding:0px 40px 0px 40px !important;
	-padding:0px 40px 0px 40px;	
	/* margin-left:400px; */
	opacity:0.7;
	filter : alpha(opacity=70);
	padding-top:0px
}
ul.ie_decal {
	/* -margin-left:450px; */
}
div#bandeau2 {
	float:left;
	position:relative;
	top:5px;
	left:200px;
	}
li/* Elements des listes */      
{ 
	background: transparent url(../assets/images/bullet_yellow.gif) no-repeat 0 2px;
    list-style-type: none;
    padding-left: 1.2em;
}	
div.user_guide ul/* Elements des listes */      
{ 	
		position: relative !important;
		list-style-type: none!important;
		padding-left: 40px;
		list-style:url(../assets/images/silk_icons/bullet_yellow.png) !important;
		background-repeat:no-repeat!important;
		background-position:0px 5px!important;
}
table {
	max-width:1124px;
	background-color:#CCC;
	table-layout:fixed;
}
th {
	background-color:#748386;
	padding:3px;
	font-size:11pt;
	font-weight:bold;
	color:#ffffff;
	}
.vert { 
		background-color: #f0f0f0;
}

.rouge { 
		background-color:#e2e2e2;
}
blockquote
{
	border:solid 1px #A9BFCB; 
	margin:10px 10px 10px 10px;
	padding:5px 45px 5px 41px;
	background-color:#EEE; /* #D2DEE4; */
	background-position:left top;
	background-repeat:no-repeat; */
}
blockquote p
{
	color:#0B1013;
	font-family: "Lucida Grande", "Lucida Sans Unicode", Arial, Helvetica, Sans-Serif;
}
table.pagetable {
	-moz-border-radius: 5px 5px 5px 5px;
	-webkit-border-radius: 5px 5px 5px 5px;
	border-radius: 5px 5px 5px 5px;
	font-size: 1em;
	border: 1px solid #ccc;
	width: 80%;
	margin: 5px auto;
	width:100%;
	table-layout: fixed;	
}
table.pagetable th {
	color: #464646;
	text-shadow: 0 1px 0 #FFFFFF;
	background: #CCCCCC url("../assets/images/banner.png") repeat-x left -33px;
	height: 45px;
	text-align: left;
	white-space: nowrap;
	padding-left: 5px;
	padding-right: 5px;
}
table.pagetable th a {
	color: #000;
}
table.pagetable th.active {
	color: #333;
}
table.pagetable th.active a {
	color: #333;
	text-decoration: underline;
}
table.pagetable th a:hover {
	color: #333;
	text-decoration: underline;
}
table.pagetable tr {
	height: 2.5em;
}
table.pagetable td {
	padding-left: 5px;
	padding-right: 5px;
	word-wrap: break-word;
}
table.pagetable a {
	/* color: #000; */
}
table.pagetable th.pagepos {
	text-align: center;
}
a {
	color: #666;
    text-decoration : none;
}
</style>
<script type="text/javascript" src="../coloration/scripts/shCore.js"></script>
<script type="text/javascript" src="../coloration/scripts/shBrushAsm.js"></script>
<script type="text/javascript" src="../coloration/scripts/shBrushCpp.js"></script>
<script type="text/javascript" src="../coloration/scripts/shBrushPerl.js"></script>
</head>
<body style="background-color:#FFF">
<!--[if !IE 6]><!-->
<?= $header ?>
<!--><![endif]-->
<div class="sub_body">
<?= $html ?>
</div>
<!--[if !IE 6]><!-->
<?php echo $footer ?>
<!--><![endif]-->
<script type="text/javascript">
     SyntaxHighlighter.all()
</script>
</body>
</html>	
